# Generated by Django 4.0.4 on 2022-04-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_user_phone_produits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='345656', max_length=100),
        ),
    ]
